# Generated by Django 2.2.20 on 2021-08-19 09:57
import csv
import os

from django.conf import settings
from django.contrib.gis.geos import Point
from django.db import transaction


def import_helper_table_into_zwaarverkeerhelpertable(apps, schema_editor):
    # legacy code, ZwaarVerkeerHelperTable has been renamed to Camera.
    # This method is needed because of an old migration (0015)
    ZwaarVerkeerHelperTable = apps.get_model('passage', 'ZwaarVerkeerHelperTable')
    _import_helper_table(ZwaarVerkeerHelperTable)


def import_helper_table_into_camera(apps, schema_editor):
        Camera = apps.get_model('passage', 'Camera')
        _import_helper_table(Camera)


def _import_helper_table(CameraModel):
    helper_table_csv_path = os.path.join(
        settings.BASE_DIR, 'passage', 'helpertable.csv'
    )

    with transaction.atomic():
        CameraModel.objects.all().delete()

        with open(helper_table_csv_path, newline='') as csvfile:
            reader = csv.DictReader(csvfile, dialect='excel', delimiter=',')

            inserts = []
            for row in reader:
                for key in row.keys():
                    row[key] = None if row[key] == '' else row[key]

                lat = row.pop('latitude')
                lon = row.pop('longitude')
                if lat is not None and lon is not None:
                    row['location'] = Point(
                        float(lat), float(lon), srid=4326
                    )

                # the following fields have been added to the initial table
                # during migrations. Depending on the migration, fields may
                # not exist.
                existing_field_names = [f.name for f in CameraModel._meta.fields]
                later_added_fields = [
                    # migration 0015
                    'camera_id',
                    'vma_linknr',
                    # migration 0029
                    'rijrichting_correct'
                ]

                for fieldname in later_added_fields:
                    if fieldname not in existing_field_names:
                        row.pop(fieldname)

                inserts.append(CameraModel(**row))

        CameraModel.objects.bulk_create(inserts)
