# Generated by Django 2.2.20 on 2021-08-19 09:57
import csv
import os

from django.conf import settings
from django.contrib.gis.geos import Point
from django.db import transaction


def import_helper_table_into_zwaarverkeerhelpertable(apps, schema_editor):
    # legacy code, ZwaarVerkeerHelperTable has been renamed to Camera.
    # This method is needed because of an old migration (0015)
    ZwaarVerkeerHelperTable = apps.get_model('passage', 'ZwaarVerkeerHelperTable')
    _import_helper_table(ZwaarVerkeerHelperTable)


def import_helper_table_into_camera(apps, schema_editor):
        Camera = apps.get_model('passage', 'Camera')
        _import_helper_table(Camera)


def _import_helper_table(CameraModel):
    helper_table_csv_path = os.path.join(
        settings.BASE_DIR, 'passage', 'helpertable.csv'
    )

    with transaction.atomic():
        CameraModel.objects.all().delete()

        with open(helper_table_csv_path, newline='') as csvfile:
            reader = csv.DictReader(csvfile, dialect='excel', delimiter=',')

            inserts = []
            for row in reader:
                for key in row.keys():
                    row[key] = None if row[key] == '' else row[key]

                lat = row.pop('latitude')
                lon = row.pop('longitude')
                if lat is not None and lon is not None:
                    row['location'] = Point(
                        float(lat), float(lon), srid=4326
                    )

                if CameraModel.__name__ == 'ZwaarVerkeerHelperTable':
                    # we call this in migration 0015, and this version of the
                    # table does not have these new fields (added in 0025).
                    row.pop('camera_id')
                    row.pop('vma_linknr')

                inserts.append(CameraModel(**row))

        CameraModel.objects.bulk_create(inserts)
