# Generated by Django 4.0.2 on 2022-03-01 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passage', '0017_igorhouraggregation'),
    ]

    operations = [
        migrations.AddField(
            model_name='passage',
            name='aantal_assen',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='passage',
            name='aantal_staanplaatsen',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='passage',
            name='aantal_wielen',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='passage',
            name='aantal_zitplaatsen',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='passage',
            name='breedte',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='passage',
            name='co2_uitstoot_gecombineerd',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='passage',
            name='co2_uitstoot_gewogen',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='passage',
            name='handelsbenaming',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='passage',
            name='kenteken_hash',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='passage',
            name='lengte',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='passage',
            name='massa_ledig_voertuig',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='passage',
            name='maximum_massa_trekken_geremd',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='passage',
            name='maximum_massa_trekken_ongeremd',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='passage',
            name='milieuklasse_eg_goedkeuring_zwaar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='heavytraffichouraggregation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='igorhouraggregation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='igorhouraggregation',
            name='taxi_indicator',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='passage',
            name='automatisch_verwerkbaar',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='passage',
            name='brandstoffen',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='passage',
            name='extra_data',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='passage',
            name='kenteken_karakters_betrouwbaarheid',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='passage',
            name='taxi_indicator',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='passagehouraggregation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='passagehouraggregation',
            name='taxi_indicator',
            field=models.BooleanField(null=True),
        ),
    ]
