# Generated by Django 3.2.7 on 2021-10-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passage', '0017_igorhouraggregation'),
    ]

    operations = [
        migrations.AddField(
            model_name='passage',
            name='aantal_assen',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='passage',
            name='aantal_staanplaatsen',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='passage',
            name='aantal_wielen',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='passage',
            name='aantal_zitplaatsen',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='passage',
            name='breedte',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='passage',
            name='co2_uitstoot_gecombineerd',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='passage',
            name='co2_uitstoot_gewogen',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='passage',
            name='handelsbenaming',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='passage',
            name='kenteken_hash',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='passage',
            name='lengte',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='passage',
            name='massa_ledig_voertuig',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='passage',
            name='maximum_massa_trekken_geremd',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='passage',
            name='maximum_massa_trekken_ongeremd',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='passage',
            name='milieuklasse_eg_goedkeuring_zwaar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='passage',
            name='vervaldatum_apk',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='passage',
            name='wam_verzekerd',
            field=models.NullBooleanField(),
        ),
    ]
