# Generated by Django 4.0.2 on 2022-03-08 14:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('passage', '0019_passage_volgnummer'),
    ]

    operations = [
        migrations.AddField(
            model_name='passage',
            name='passage_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passage',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='passage',
            name='massa_ledig_voertuig_new',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
