# Generated by Django 4.0.2 on 2022-02-16 14:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('passage', '0020_rename_id_passage_external_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passage',
            name='external_id',
            field=models.UUIDField(),
        ),
        # Note: we manually changed primary key to primary_key=False. After, we update
        # the existing primary key to match the new id field
        migrations.AddField(
            model_name='passage',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=False, serialize=False),
        ),
        migrations.RunSQL("""
            alter table passage_passage drop constraint if exists passage_passage_pkey;
            alter table passage_passage add constraint passage_passage_pkey primary key (id, passage_at);
        """),
    ]
