# Generated by Django 4.0.2 on 2022-05-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passage', '0022_alter_passage_camera_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passage',
            name='massa_ledig_voertuig_new',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
