# Generated by Django 4.0.2 on 2022-03-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passage', '0022_alter_passage_camera_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passage',
            name='maximum_massa_trekken_geremd',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='passage',
            name='maximum_massa_trekken_ongeremd',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='passage',
            name='voertuig_soort',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='passage',
            name='volgnummer',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
