# Generated by Django 4.0.2 on 2022-05-09 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passage', '0022_alter_passage_camera_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heavytraffichouraggregation',
            name='voertuig_soort',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
