# Generated by Django 4.0.2 on 2022-05-11 13:25

from django.db import migrations

from passage.helpertable_importer import import_helper_table_into_camera


class Migration(migrations.Migration):

    dependencies = [
        ('passage', '0024_alter_passagehouraggregation_voertuig_soort'),
    ]

    operations = [
        migrations.RunPython(import_helper_table_into_camera, migrations.RunPython.noop)
    ]
