# Generated by Django 4.0.2 on 2022-03-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passage', '0024_alter_passage_aantal_assen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passage',
            name='massa_ledig_voertuig',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
