# Generated by Django 4.0.2 on 2022-05-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passage', '0026_auto_20220511_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heavytraffichouraggregation',
            name='passage_at_hour',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='igorhouraggregation',
            name='camera_naam',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='igorhouraggregation',
            name='passage_at_hour',
            field=models.IntegerField(db_index=True),
        ),
    ]
