# Generated by Django 4.0.2 on 2022-05-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passage', '0027_alter_heavytraffichouraggregation_passage_at_hour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heavytraffichouraggregation',
            name='azimuth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='igorhouraggregation',
            name='azimuth',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
