# Generated by Django 4.0.4 on 2022-06-30 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passage', '0032_heavytrafficminuteaggregation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heavytraffichouraggregationv2',
            name='co2_uitstoot_gecombineerd',
        ),
        migrations.RemoveField(
            model_name='heavytraffichouraggregationv2',
            name='co2_uitstoot_gewogen',
        ),
        migrations.RemoveField(
            model_name='heavytraffichouraggregationv2',
            name='milieuklasse_eg_goedkeuring_zwaar',
        ),
        migrations.RemoveField(
            model_name='heavytraffichouraggregationv2',
            name='versit_klasse',
        ),
        migrations.AddField(
            model_name='heavytraffichouraggregationv2',
            name='lengte',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
