# Generated by Django 4.0.4 on 2022-06-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passage', '0033_remove_heavytraffichouraggregationv2_co2_uitstoot_gecombineerd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='rijrichting_correct',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='heavytraffichouraggregationv2',
            name='rijrichting_correct',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='heavytrafficminuteaggregation',
            name='rijrichting_correct',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
