# Generated by Django 4.0.4 on 2022-07-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passage', '0034_alter_camera_rijrichting_correct_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heavytrafficminuteaggregation',
            name='aantal_assen',
        ),
        migrations.RemoveField(
            model_name='heavytrafficminuteaggregation',
            name='aantal_wielen',
        ),
        migrations.RemoveField(
            model_name='heavytrafficminuteaggregation',
            name='breedte',
        ),
        migrations.RemoveField(
            model_name='heavytrafficminuteaggregation',
            name='co2_uitstoot_gecombineerd',
        ),
        migrations.RemoveField(
            model_name='heavytrafficminuteaggregation',
            name='co2_uitstoot_gewogen',
        ),
        migrations.RemoveField(
            model_name='heavytrafficminuteaggregation',
            name='datum_eerste_toelating',
        ),
        migrations.RemoveField(
            model_name='heavytrafficminuteaggregation',
            name='kenteken_land',
        ),
        migrations.RemoveField(
            model_name='heavytrafficminuteaggregation',
            name='maximum_massa_trekken_geremd',
        ),
        migrations.RemoveField(
            model_name='heavytrafficminuteaggregation',
            name='maximum_massa_trekken_ongeremd',
        ),
        migrations.RemoveField(
            model_name='heavytrafficminuteaggregation',
            name='milieuklasse_eg_goedkeuring_zwaar',
        ),
        migrations.RemoveField(
            model_name='heavytrafficminuteaggregation',
            name='versit_klasse',
        ),
        migrations.AlterField(
            model_name='heavytrafficminuteaggregation',
            name='lengte',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
