# Generated by Django 4.0.4 on 2022-09-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passage', '0035_remove_heavytrafficminuteaggregation_aantal_assen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='heavytraffichouraggregationv2',
            name='richting',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='heavytrafficminuteaggregation',
            name='richting',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
