# Generated by Django 4.0.4 on 2022-08-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passage', '0035_remove_heavytrafficminuteaggregation_aantal_assen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passage',
            name='camera_naam',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
