# By default, Compose reads two files, a docker-compose.yml and an
# optional docker-compose.override.yml file. By convention,
# the docker-compose.yml contains your base configuration. The
# override file, as its name implies, can contain configuration
# overrides for existing services or entirely new services.
# See https://docs.docker.com/compose/extends/
#
# Usage: copy this file, name it ".docker-compose.override.yml" and
# set your own values.

version: "3.5"
services:
  database:
    ports:
      - "5432:5432"  # allows to run database on different port on host

  api:
    ports:
      - "8001:8000"  # allows to run app on different port on host

  dev:
    ports:
      - "8001:8000"
