version: '3.0'
services:
  iotsignals:
    image: build.datapunt.amsterdam.nl:5000/datapunt/iotsignals:${ENVIRONMENT}
    environment:
      DATABASE_NAME: iotsignals
      DATABASE_USER: iotsignals
      DATABASE_PASSWORD:
