# Generated by Django 2.1.10 on 2019-07-17 05:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleMeasurement',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('sensor', models.CharField(max_length=255)),
                ('sensortype', models.CharField(max_length=255)),
                ('latitude', models.CharField(max_length=20)),
                ('longitude', models.CharField(max_length=20)),
                ('density', models.FloatField(null=True)),
                ('speed', models.FloatField(null=True)),
                ('count', models.IntegerField(null=True)),
                ('details', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
        ),
    ]
