# Generated by Django 2.1.10 on 2019-07-10 08:59

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('sensor', models.CharField(max_length=255)),
                ('sensortype', models.CharField(max_length=255)),
                ('latitude', models.CharField(max_length=15)),
                ('longitude', models.CharField(max_length=15)),
                ('count', models.IntegerField()),
                ('details', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
        ),
    ]
