# Generated by Django 2.2.9 on 2020-03-18 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peoplemeasurement', '0004_cmsa_15min_view_20190926_1130'),
    ]
    _VIEW_NAME = "druktemonitor_quarter_view"

    sql = f"""
        CREATE VIEW {_VIEW_NAME} AS
        QuarterHourTable as(
        SELECT
            sensor,
            date_trunc('hour', timestamp) + date_part('minute', timestamp)::int / 15 * interval '15 min' as timestamp_rounded,
            avg((detail_elems ->> 'count')::integer) FILTER (WHERE detail_elems ->> 'direction' = 'down') + avg((detail_elems ->> 'count')::integer) FILTER (WHERE detail_elems ->> 'direction' = 'up') as count
        FROM
            peoplemeasurement_peoplemeasurement,
            jsonb_array_elements(details) detail_elems
        where
            timestamp >= now() - interval '15 minutes';
            and sensor in ('GAWW-01', 'GAWW-02', 'GAWW-03', 'GAWW-04', 'GAWW-05')
        group by
            timestamp_rounded
        order by
            timestamp_rounded
        )
        SELECT
            timestamp_rounded,
            round((sum(avg_count) / 473.991) * 100,0) as druktecijfer,
        FROM
            QuarterHourTable
        group by
            timestamp_rounded
        order by
            timestamp_rounded;
    """

    reverse_sql = f"drop view if exists {_VIEW_NAME};"


    operations = [
        migrations.RunSQL(
            sql=sql,
            reverse_sql=reverse_sql
        ),
    ]
