# Generated by Django 2.2.9 on 2020-03-18 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peoplemeasurement', '0005_druktemonitor_quarter_view_20200318_0847'),
    ]
    _VIEW_NAME = "druktemonitor_hourly_view"

    sql = f"""
        CREATE VIEW {_VIEW_NAME} AS
        with HourlyTable as(
        select
            sensor,
            date_trunc('hour', timestamp) as timestamp_rounded,
            avg((detail_elems ->> 'count')::integer) FILTER (WHERE detail_elems ->> 'direction' = 'down') + avg((detail_elems ->> 'count')::integer) FILTER (WHERE detail_elems ->> 'direction' = 'up') as count
        FROM
            peoplemeasurement_peoplemeasurement,
            jsonb_array_elements(details) detail_elems
        where
            date_trunc('hour', timestamp) = date_trunc('hour', now() - interval '1 hours')
            and sensor in ('GAWW-01', 'GAWW-02', 'GAWW-03', 'GAWW-04', 'GAWW-05')
        group by
            sensor,
            timestamp_rounded
        order by
            sensor,
            timestamp_rounded
        )
        select
            timestamp_rounded,
            round((sum(count) / 473.991) * 100,0) as druktecijfer
        from
            HourlyTable
        group by
            timestamp_rounded
        order by
            timestamp_rounded;
    """

    reverse_sql = f"drop view if exists {_VIEW_NAME};"


    operations = [
        migrations.RunSQL(
            sql=sql,
            reverse_sql=reverse_sql
        ),
    ]
