# Generated by Django 2.2.20 on 2021-08-19 09:57

from django.db import migrations

from passage.helpertable_importer import (
    import_helper_table_into_zwaarverkeerhelpertable,
)


class Migration(migrations.Migration):

    dependencies = [
        ('passage', '0014_zonezwaarverkeer_zwaarverkeerhelpertable'),
    ]

    operations = [
        migrations.RunPython(
            import_helper_table_into_zwaarverkeerhelpertable, migrations.RunPython.noop
        )
    ]
