# Generated by Django 4.0.2 on 2022-03-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passage', '0020_passage_passage_id_alter_passage_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passage',
            name='passage_id',
            field=models.UUIDField(),
        ),
        migrations.AlterUniqueTogether(
            name='passage',
            unique_together={('passage_id', 'volgnummer', 'passage_at')},
        ),
        migrations.AlterField(
            model_name='passage',
            name='volgnummer',
            field=models.IntegerField(default=1),
        ),
        migrations.RemoveField(
            model_name='passage',
            name='massa_ledig_voertuig'
        ),
        migrations.RenameField(
            model_name='passage',
            old_name='massa_ledig_voertuig_new',
            new_name='massa_ledig_voertuig'
        )
    ]
