# Generated by Django 4.0.2 on 2022-03-30 14:58

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passage', '0021_alter_passage_passage_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passage',
            name='aantal_assen',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passage',
            name='aantal_staanplaatsen',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passage',
            name='aantal_wielen',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passage',
            name='aantal_zitplaatsen',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passage',
            name='automatisch_verwerkbaar',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passage',
            name='brandstoffen',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passage',
            name='breedte',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passage',
            name='camera_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='passage',
            name='camera_kijkrichting',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passage',
            name='camera_locatie',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='passage',
            name='camera_naam',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='passage',
            name='co2_uitstoot_gecombineerd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passage',
            name='co2_uitstoot_gewogen',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passage',
            name='datum_eerste_toelating',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passage',
            name='datum_tenaamstelling',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passage',
            name='diesel',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passage',
            name='electric',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passage',
            name='europese_voertuigcategorie',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='passage',
            name='europese_voertuigcategorie_toevoeging',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='passage',
            name='extra_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passage',
            name='gasoline',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passage',
            name='handelsbenaming',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='passage',
            name='indicatie_snelheid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passage',
            name='inrichting',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='passage',
            name='kenteken_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='passage',
            name='kenteken_karakters_betrouwbaarheid',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passage',
            name='kenteken_land',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='passage',
            name='kenteken_land_betrouwbaarheid',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='passage',
            name='kenteken_nummer_betrouwbaarheid',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='passage',
            name='lengte',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passage',
            name='maximale_constructie_snelheid_bromsnorfiets',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passage',
            name='maximum_massa_trekken_geremd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passage',
            name='maximum_massa_trekken_ongeremd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passage',
            name='merk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='passage',
            name='milieuklasse_eg_goedkeuring_zwaar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='passage',
            name='rijrichting',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passage',
            name='rijstrook',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passage',
            name='straat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='passage',
            name='taxi_indicator',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passage',
            name='toegestane_maximum_massa_voertuig',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passage',
            name='versit_klasse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='passage',
            name='voertuig_soort',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='passage',
            name='volgnummer',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='passagehouraggregation',
            name='diesel',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passagehouraggregation',
            name='electric',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passagehouraggregation',
            name='europese_voertuigcategorie',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='passagehouraggregation',
            name='gasoline',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passagehouraggregation',
            name='taxi_indicator',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passagehouraggregation',
            name='voertuig_soort',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
