# Generated by Django 4.0.2 on 2022-05-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passage', '0023_alter_heavytraffichouraggregation_voertuig_soort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passagehouraggregation',
            name='voertuig_soort',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
