# Generated by Django 4.0.4 on 2022-06-24 07:18

from django.db import migrations

from passage.helpertable_importer import import_helper_table_into_camera


class Migration(migrations.Migration):

    dependencies = [
        ('passage', '0029_camera_rijrichting_correct'),
    ]

    operations = [
        migrations.RunPython(import_helper_table_into_camera, migrations.RunPython.noop)
    ]
