# Generated by Django 4.1.10 on 2023-07-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("passage", "0036_heavytraffichouraggregationv2_richting_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HulptabelCameragebiedenTaxidashboard",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("gebiedstype", models.CharField(max_length=255)),
                ("gebied", models.CharField(max_length=255)),
                ("camera_id", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="TaxiHourAggregation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("passage_at_date", models.DateField(db_index=True, null=True)),
                ("hh", models.IntegerField()),
                ("gebiedstype", models.CharField(max_length=255)),
                ("gebied", models.CharField(max_length=255)),
                ("electric", models.IntegerField()),
                ("unieke_passages", models.IntegerField()),
                ("check_on_camera_count", models.IntegerField()),
            ],
        ),
    ]
