# Generated by Django 4.1.10 on 2023-11-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("passage", "0037_hulptabelcameragebiedentaxidashboard_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="heavytraffichouraggregationv2",
            name="aantal_staanplaatsen",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="heavytraffichouraggregationv2",
            name="aantal_zitplaatsen",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="heavytraffichouraggregationv2",
            name="breedte",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="heavytraffichouraggregationv2",
            name="diesel",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="heavytraffichouraggregationv2",
            name="electric",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="heavytraffichouraggregationv2",
            name="gasoline",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="heavytraffichouraggregationv2",
            name="handelsbenaming",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="heavytraffichouraggregationv2",
            name="kenteken_land",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="heavytraffichouraggregationv2",
            name="merk",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="heavytrafficminuteaggregation",
            name="aantal_staanplaatsen",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="heavytrafficminuteaggregation",
            name="aantal_zitplaatsen",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="heavytrafficminuteaggregation",
            name="breedte",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="heavytrafficminuteaggregation",
            name="diesel",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="heavytrafficminuteaggregation",
            name="electric",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="heavytrafficminuteaggregation",
            name="gasoline",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="heavytrafficminuteaggregation",
            name="handelsbenaming",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="heavytrafficminuteaggregation",
            name="kenteken_land",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="heavytrafficminuteaggregation",
            name="merk",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
